source/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from .views import home
from django.urls import path
from .views import (admin_login,  admin_logout, admin_dashboard,staff_login, staff_logout,staff_dashboard)
from . import views
from diagnostic_centers.views import *

admin.site.site_header = 'LMS'                   
admin.site.index_title = 'LMS'                
admin.site.site_title = 'LMS'



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('', include('custom_users.urls', namespace='custom_users')),
    path('', include('diagnostic_centers.urls', namespace='diagnostic_centers')),
    path('chat/', include(('chat_messages.urls', 'chat_messages'), namespace='chat_messages')),
    path('accounts/', include('allauth.urls')),

    path('supervisor-login/', admin_login, name='admin-login'),
    path('supervisor-logout/', admin_logout, name='admin-logout'),
    path('supervisor-dashboard/<username>/', admin_dashboard, name='admin-dashboard'),
    # path('supervisor-chat/',views.supervisor_chat, name="supervisor_chat"),
    path('student-login/', staff_login, name='staff-login'),
    path('student-logout/', staff_logout, name='staff-logout'),
    path('student-dashboard/<username>/', staff_dashboard, name='staff-dashboard'),
    path('student-dashboard/<int:id>/<username>/', staff_dashboard, name='staff-dashboards'),
    # path('chat/',views.chat, name="chat"),
    # path('load-messages/', views.load_messages, name='load_messages'),
    path('questionnaire/', questionnaire, name='questionnaire'),

   

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/report_processing/all_reports.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>All Reports | ODLRS</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />

    <style>
        p {
            margin-bottom: 0;
        }
    </style>

</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand text-warning" href="#"><b>ODLRS</b></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto">

{#                    <li class="nav-item">#}
{#                        <a class="nav-link text-white" href="#"> Report Lists </a>#}
{#                    </li>#}

                    <li class="nav-item">
                        <!-- <button type="submit"> -->
                        <a class="nav-link text-white" href="{% url 'tests:all-tests-list-staff-admin' %}">Recently
                            Added
                            Tests</a>
                        <!-- </button> -->
                    </li>

{#                    <li class="nav-item">#}
{#                        <!-- <button type="submit"> -->#}
{#                        <a class="nav-link text-warning"#}
{#                            href="http://localhost:8000/staff-dashboard/labaid_staff_1">Staff#}
{#                            Dashboard</a>#}
{#                        <!-- </button> -->#}
{#                    </li>#}

{#                    <li class="nav-item">#}
{#                        <!-- <button type="submit"> -->#}
{#                        <a class="nav-link text-white" href="{% url 'diagnostic_centers:staff-logout' %}">Logout</a>#}
{#                        <!-- </button> -->#}
{#                    </li>#}

                </ul>
            </div>
        </div>
    </nav>


    <table class="table table-striped table-bordered table-hover mb-4">
        <thead>
        <tr class="bg-primary text-white">
            <th colspan="6"> All Verified Reports </th>
        </tr>
        <tr style="background-color: forestgreen">
            <th>SL NO.</th>
            <th> Test Names </th>
            <th> Validation DateTime </th>
            <th> Reports </th>
            <th> Messages </th>

        </tr>
        </thead>

        <tbody>

        {% for report in all_reports_query %}

            <tr>
                <td> {{ forloop.counter }} </td>
                <td><a href="{% url 'report_processing:single-report-details' report.id %}"><b style="color: green">
                    {{ report.approved_order.test_info.test_name }}
                </b></a></td>
                <td><b style="color: deeppink">{{ report.datetime }}</b></td>
                <td><a href="/media/reports_PDF/report_demo.pdf"><b style="color: blue">{{ report.upload_report }}</b></a></td>
                <td><b style="color: blue">{{ report.send_message }}</b></td>
            </tr>

        {% endfor %}

        </tbody>
    </table>

    <!-- All reports Paginator -->
    <ul class="pagination">
        <li class="page-item">

            {% if all_reports_query.has_previous %}
                <a class="page-link" href="?page={{ all_reports_query.previous_page_number }}"
                   aria-label="Previous">
                    <span aria-hidden="false">&laquo;</span>
                </a>
            {% endif %}

        </li>
        <li class="page-item">
            <a class="page-link" href="#">Page {{ all_reports_query.number }} of
                {{ all_reports_query.paginator.num_pages }}.</a>
        </li>
        <li class="page-item">

            {% if all_reports_query.has_next %}

                <a class="page-link" href="?page={{ all_reports_query.next_page_number }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            {% endif %}
        </li>
    </ul>
    <!-- All reports Paginator -->


    <br>
    <br>
    <div class="footer bg-dark text-white text-center py-2">
        <p class="mb-0"> &copy; Copyrights 2019. All rights reserved. </p>
    </div>

</body>

</html>

templates/report_processing/complete_due_payment.html
{% extends 'base.html' %}

{% block title %}Complete Due Payment Form | ODLRS{% endblock %}

{% block content %}
<div>
    <div class="row my-5">
        <div class="col-6 offset-3 text-cente">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h3 class="mb-0">Complete Due Payment</h3>
                </div>
                <div class="card-body">

{#                    <form action="{% url 'tests:order' test_id %}" method="post">#}
                    <form action="#" method="post">
                        {% csrf_token %}

                        {{ complete_due_payment_form.as_p }}
                        <br>
                        <button type="submit" class="btn btn-primary btn-sm">
                            PAYMENT
                        </button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/report_processing/single_report_details.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Report Details | ODLRS</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fakeLoader.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <script src="{% static 'js/jquery.min.js' %}"></script>
</head>

<body class="common-bg pt-0">
    <!-- loader -->
    <div class="fakeLoader"></div>
    <!-- loader -->

    <div class="container my-5">
        <div class="single-reports card-width">
            <div class="card">
                <div class="card-header bg-dark text-white text-center
                        py-3">
                    <h3 class="mb-0">Completed Order Details</h3>
                </div>
                <div class="card-bottom-img"></div>

                <div class="card-body">
                    <!-- Flag -->
                    {% if report_details.approved_order.payment_type == 'Half Payment' %}
                    <div class="alert alert-danger">
                        <strong class="">Payment Due {{ due_price }}Tk.</strong>
                        <!-- <a href="#" class="text-danger" data-dismiss="alert">&times;</a> -->
                    </div>
                    {% else %}
                    <div class="alert alert-success">
                        <strong>Full Payment Complete</strong>
                        <!-- <a href="#" class="text-succes float-right" data-dismiss="alert">&times;</a> -->
                    </div>
                    {% endif %}

                    <!-- Flag -->
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p for="">Name</p>
                                <p>
                                    {{ report_details.approved_order.client_info.user.customer_profile.profile_name }}
                                </p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Test Name</p>
                                <p>{{ report_details.approved_order.test_info.test_name }}</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Email</p>
                                <p>{{ report_details.approved_order.client_info.user.email }}</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Contact</p>
                                <p>{{ report_details.approved_order.client_info.user.customer_profile.contact_no }}
                                </p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Booked DateTime</p>
                                <p>
                                    {{ report_details.approved_order.booked_date }}
                                    ({{ report_details.approved_order.booked_time_slot }})
                                </p>
                            </div>
                        </div>

                        {% if report_details.approved_order.payment_type == 'Half Payment' %}

                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-danger">
                                <p>Received Payment</p>
                                <p>{{ total_price }}</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-danger">
                                <p>Due</p>
                                <p>{{ due_price }}</p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-danger">
                                <p>Payment Status</p>
                                <p>
                                    {{ report_details.approved_order.payment_type }}
                                    ({{ report_details.approved_order.payment_method}})
                                </p>
                            </div>
                        </div>
                        {% else %}

                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Total Price</p>
                                <p> {{ total_price }}Tk. </p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Received Payment</p>
                                <p> {{ total_price }}Tk. </p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Payment Status</p>
                                <p>
                                    {{ report_details.approved_order.payment_type }}
                                    ({{ report_details.approved_order.payment_method}})
                                </p>
                            </div>
                        </div>
                        {% endif %}

                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group text-succes">
                                <p>Validation DateTime</p>
                                <p>
                                    {{ report_details.datetime }}
                                </p>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-6 col-md-6">
                            <div class="group">
                                <p class="">Download Report</p>
                                <a href="/media/reports_PDF/report_demo.pdf"
                                    class="text-danger">{{ report_details.upload_report }}</a>
                            </div>
                        </div>

                        <div class="col">
                            <div class="row mt-2">
                                {% if request.user.is_authenticated %}
                                <div class="col-xs-12 col-sm-6 col-md-6">
                                    <a href="{% url 'home' %}" class="btn btn-warning w-100">Back to Home
                                    </a>
                                </div>
                                    {% if report_details.approved_order.payment_type == 'Half Payment' %}
                                    <div class="col-xs-12 col-sm-6 col-md-6">
                                    <a class="btn btn-success w-100"
                                        href="{% url 'report_processing:complete-due-payment' report_details.approved_order.id report_details.id %}">
                                        CompletePayment
                                    </a>
                                    </div>
                                    {% endif %}
                                {% endif %}
{#                                {% if report_details.approved_order.payment_type == 'Half Payment' %}#}
{#                                <div class="col-xs-12 col-sm-6 col-md-6">#}
{#                                    <a class="btn btn-success w-100"#}
{#                                        href="{% url 'report_processing:complete-due-payment' report_details.approved_order.id report_details.id %}">#}
{#                                        CompletePayment#}
{#                                    </a>#}
{#                                </div>#}
{#                                {% endif %}#}
                            </div>

                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    </div>

    <script src="{% static 'js/fakeLoader.min.js' %}"></script>
    <script>
        $.fakeLoader();
    </script>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>