custom_users/urls.py
from django.urls import path

from .views import ( profile,    profile_edit)

app_name = 'custom_users'

urlpatterns = [
    # path('login/', MyLoginView.as_view(), name='account_login'),
    path('profile/', profile, name='profile'),
    path('profile-edit/', profile_edit, name='profile-edit'),
]

diagnostic_centers/urls.py
from django.urls import path
from .views import (admin_login,  admin_logout, admin_dashboard,staff_login, staff_logout,staff_dashboard)
from .views import q
from . import views
app_name = 'diagnostic_centers'


from django.urls import path
from .views import admin_dashboard

from django.urls import path
from . import views


from django.urls import path
from . import views



# urls.py
from django.urls import path
from . import views




urlpatterns = [
    path('supervisor-login/', admin_login, name='admin-login'),
    path('supervisor-logout/', admin_logout, name='admin-logout'),
    path('supervisor-dashboard/<username>/', admin_dashboard, name='admin-dashboard'),

    path('student-login/', staff_login, name='staff-login'),
    path('student-logout/', staff_logout, name='staff-logout'),
    path('student-dashboard/<username>/', staff_dashboard, name='staff-dashboard'),
    path('student-dashboard/<int:id>/<username>/', staff_dashboard, name='staff-dashboards'),

 
    path('upload/', views.project_upload, name='project_upload'),
    path('list/', views.project_list, name='project_list'),

    path('project_approval/<int:upload_id>/<username>/', views.project_approval, name='project_approval'),
    

]

source/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from .views import home
from django.urls import path
from .views import (admin_login,  admin_logout, admin_dashboard,staff_login, staff_logout,staff_dashboard)
from . import views
from diagnostic_centers.views import *

admin.site.site_header = 'LMS'                   
admin.site.index_title = 'LMS'                
admin.site.site_title = 'LMS'



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('', include('custom_users.urls', namespace='custom_users')),
    path('', include('diagnostic_centers.urls', namespace='diagnostic_centers')),
    path('chat/', include(('chat_messages.urls', 'chat_messages'), namespace='chat_messages')),
    path('accounts/', include('allauth.urls')),

    path('supervisor-login/', admin_login, name='admin-login'),
    path('supervisor-logout/', admin_logout, name='admin-logout'),
    path('supervisor-dashboard/<username>/', admin_dashboard, name='admin-dashboard'),
    # path('supervisor-chat/',views.supervisor_chat, name="supervisor_chat"),
    path('student-login/', staff_login, name='staff-login'),
    path('student-logout/', staff_logout, name='staff-logout'),
    path('student-dashboard/<username>/', staff_dashboard, name='staff-dashboard'),
    path('student-dashboard/<int:id>/<username>/', staff_dashboard, name='staff-dashboards'),
    # path('chat/',views.chat, name="chat"),
    # path('load-messages/', views.load_messages, name='load_messages'),
    path('questionnaire/', questionnaire, name='questionnaire'),

   

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diagnostic_centers/forms.py
from django import forms
from django.forms import TextInput
from .models import DiagnosticAdmin, Students, Groups
import pandas as pd

class AdminLoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model = DiagnosticAdmin
        fields = ['username', 'password']
        widgets = {
            'username': TextInput(attrs={'class': 'form-control'}),
            'password': TextInput(attrs={'class': 'form-control'}),
        }


class StaffLoginForm(forms.ModelForm):
    class Meta:
        model = Students
        fields = ['username', 'password']
        widgets = {
            'username': TextInput(attrs={'class': 'form-control'}),
            'password': TextInput(attrs={'class': 'form-control'}),
        }


#####################################################################################
from django import forms
from .models import Questionnaire

class QuestionnaireForm(forms.ModelForm):
    class Meta:
        model = Questionnaire
        exclude = ['prediction']
        fields = '__all__'
        widgets = {
            'user': forms.HiddenInput(),
        }
    def clean_user(self):
        user = self.cleaned_data['user']
        if Questionnaire.objects.filter(user=user).exists():
            raise forms.ValidationError("Questionnaire already exists for this user.")
        return user


from django import forms
from .models import Groups

class GroupsForm(forms.ModelForm):
    class Meta:
        model = Groups
        fields = ['name', 'topic', 'student1', 'student2', 'student3', 'supervisor', 'file']



from django import forms
from .models import ProjectUploads

from django import forms
from .models import ProjectUploads

# class ProjectUploadForm(forms.ModelForm):
#     class Meta:
#         model = ProjectUploads
#         fields = ['project_stuff','user', 'title', 'description', 'upload_file', 'remarks']


from django import forms
from .models import ProjectUploads

# class ProjectUploadForm(forms.ModelForm):
#     class Meta:
#         model = ProjectUploads
#         fields = ['user', 'title', 'description', 'upload_file', 'remarks']

class ProjectUploadForm(forms.ModelForm):
    class Meta:
        model = ProjectUploads
        fields = ['user', 'title', 'description', 'upload_file', 'remarks']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Make the 'user' field read-only
        self.fields['user'].widget.attrs['readonly'] = 'readonly'

diagnostic_centers/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.db.models import Q
from .models import DiagnosticAdmin, Students, Questionnaire
from .forms import AdminLoginForm, StaffLoginForm
from .forms import GroupsForm
def search_paginator(request):
    Centers = Students.objects.all()

    query = request.GET.get('q')
    if query:
        Centers = Centers.filter(
            Q(name__icontains=query) |
            Q(website__icontains=query)
        )
        print(Centers)

    paginator = Paginator(Centers, 12)
    page = request.GET.get('page')
    all_centers = paginator.get_page(page)

    context = {'Centers': all_centers,}
    template_name = 'diagnostic_centers/all_centers.html'

    return render(request, template_name, context)


def admin_login(request):
    import pandas as pd
    from random import sample
    from .models import DiagnosticAdmin, Questionnaire, Groups
    import logging
    def fetch_records():
        students = list(Questionnaire.objects.all().order_by('prediction'))
        num_students = len(students)
        groups = []

        supervisor_fields_and_names = list(DiagnosticAdmin.objects.values_list('field', 'username').distinct())

        supervisors_by_field = {}
        for supervisor_field, supervisor_name in supervisor_fields_and_names:
            key = (supervisor_field, supervisor_name)
            supervisors_by_field[key] = []

        for student in students:
            student_field = student.prediction
            for supervisor_field, supervisor_name in supervisor_fields_and_names:
                if supervisor_field in student_field:
                    key = (supervisor_field, supervisor_name)
                    supervisors_by_field[key].append(student)
                    break

        print("Supervisor Dic : ", supervisors_by_field)

        for key, supervisor_students in supervisors_by_field.items():
            supervisor_field, supervisor_name = key
            num_supervisor_students = len(supervisor_students)
            num_groups = (num_supervisor_students + 2) // 3
            for i in range(num_groups):
                group_students = supervisor_students[i * 3: (i + 1) * 3]
                group = {
                    # 'Supervisor Field': supervisor_field,
                    'Supervisor': supervisor_name,
                    'Students': [student.user for student in group_students],
                    'Predictions': [student.prediction for student in group_students]
                }
                groups.append(group)

        return groups



    record_groups = fetch_records()
    df = pd.DataFrame(record_groups)
    print(df)

    import sqlite3
    import pandas as pd

    conn = sqlite3.connect('db.sqlite3')

    create_table_query = '''
        CREATE TABLE IF NOT EXISTS new_project_group (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            supervisor TEXT,
            student1 TEXT,
            student2 TEXT,
            student3 TEXT,
            prediction TEXT
        )
    '''
    conn.execute(create_table_query)
    num = 0
    for _, row in df.iterrows():
        supervisor = row['Supervisor']
        
        try:
            student1 = str(row['Students'][0])
        except:student1 = ''

        try:
            student2 = str(row['Students'][1])
        except:student2 = ""
        try:
            student3 = str(row['Students'][2])
        except:student3 = ''

        predictions = ', '.join(row['Predictions'])

        select_query = '''
            SELECT COUNT(*) FROM new_project_group
            WHERE supervisor = ? AND student1 = ? AND student2 = ? AND student3 = ? AND prediction = ? AND approved= ?
        '''
        
        try:
            duplicate_check = conn.execute(select_query, (supervisor, student1, student2, student3, predictions, False)).fetchone()[0]
        except:pass

        if duplicate_check == 0:  
            insert_query = '''
                INSERT INTO new_project_group (supervisor, student1, student2, student3, prediction, approved)
                VALUES (?, ?, ?, ?, ?, ?)
            '''
            conn.execute(insert_query, (supervisor, student1, student2, student3, predictions, False))
            insert_query = '''
                INSERT INTO chat_messages_room (supervisor, student1, student2, student3, name, description)
                VALUES (?, ?, ?, ?, ?, ?)
            '''
            conn.execute(insert_query, (supervisor, student1, student2, student3, predictions, ''))
            num += 3
            print("Record inserted successfully.")

    conn.commit()
    conn.close()

    admin_login_form = AdminLoginForm()

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        try:
            DiagnosticAdmin.objects.get(username=username, password=password)
            return redirect('diagnostic_centers:admin-dashboard', username)

        except DiagnosticAdmin.DoesNotExist:
            return redirect('diagnostic_centers:admin-login')

    template = 'diagnostic_centers/admin_login.html'

    context = {'admin_login_form': admin_login_form}

    return render(request, template, context)


################################################################################################################

def admin_dashboard(request, username=None):
    project_uploads = ProjectUploads.objects.all()
    admin2 = DiagnosticAdmin.objects.get(username=username)
    new_groups = NewProjectGroup.objects.all()
    if request.method == 'POST':
        form = GroupsForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    else:
        form = GroupsForm()
    admin = DiagnosticAdmin.objects.all()
    def fetch_records():
        students = list(Questionnaire.objects.all().order_by('prediction'))
        num_students = len(students)
        groups = []

        supervisor_fields_and_names = list(DiagnosticAdmin.objects.values_list('field', 'username').distinct())

        supervisors_by_field = {}
        for supervisor_field, supervisor_name in supervisor_fields_and_names:
            key = (supervisor_field, supervisor_name)
            supervisors_by_field[key] = []

        for student in students:
            student_field = student.prediction
            for supervisor_field, supervisor_name in supervisor_fields_and_names:
                if supervisor_field in student_field:
                    key = (supervisor_field, supervisor_name)
                    supervisors_by_field[key].append(student)
                    break

        # print("Supervisor Dic : ", supervisors_by_field)

        for key, supervisor_students in supervisors_by_field.items():
            supervisor_field, supervisor_name = key
            num_supervisor_students = len(supervisor_students)
            num_groups = (num_supervisor_students + 2) // 3
            for i in range(num_groups):
                group_students = supervisor_students[i * 3: (i + 1) * 3]
                group = {
                    'Supervisor': supervisor_name,
                    'Students': [student.user for student in group_students],
                    'Predictions': [student.prediction for student in group_students]
                }
                groups.append(group)

        return groups



    import pandas as pd
    from chat_messages.models import Room
    record_groups = fetch_records()
    df = pd.DataFrame(record_groups)
    num = 0
    supervisor_username = admin2.username
    student = list()
    num2 = 0
    for _, row in df.iterrows():
        num2 += 1
        supervisor = row['Supervisor']
        title = list(row["Predictions"])
        project_id = ''
        student1 = str(row['Students'][num])
        new_projects = list(NewProjectGroup.objects.values_list('pk', 'student1').distinct())
        for new_project in new_projects:
            new_project2 = new_project[1]
            if str(new_project2).lower() == str(student1).lower():
                project_id =  new_project[0]
                # print(project_id)
        try:
            student2 = str(row['Students'][num+1])
        except:student2 = ""
        try:
            student3 = str(row['Students'][num+2])
        except:student3 = ''

        if str(supervisor) == str(supervisor_username):
            student.append(
                {
                    'sid' : project_id,
                    'Supervisor' : supervisor,
                    'Student1' : student1,
                    'Student2' : student2,
                    'Student3' : student3,
                    'Title' : title[0],
                },
            )
        else:
            pass
    page = request.GET.get('page')
    groups = Groups.objects.all()
    title = str(df["Predictions"]).split(',')[0]
    template = ['diagnostic_centers/admin_dashboard.html', 'home.html']
    
    context = {
        'admin': admin,
        'groups': groups,
        'form': form,
        'admin' : admin,
        'students': student,
        'new_groups':new_groups,
        'admin2': admin2,
        'project_uploads': project_uploads,
        # 'sid' : project_id,
    }
    return render(request, template, context)
  

def admin_logout(request):
    messages.success(request, 'Logged Out.', extra_tags='html_safe')
    return redirect('diagnostic_centers:admin-login')

def staff_login(request):
    staff_login_form = StaffLoginForm()

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        try:
            Students.objects.get(username=username, password=password)
            return redirect('diagnostic_centers:staff-dashboard', username)
        except Students.DoesNotExist:
            return redirect('diagnostic_centers:staff-login')
    template = 'diagnostic_centers/staff_login.html'

templates/diagnostic_centers/admin_dashboard.html
{% load static %}
{% load custom_tags %}


<!doctype html>
<html lang="en">

<head>
    <title>Supervisor Dashboard</title>
    <!-- Add Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <!-- Add your custom CSS styles if needed -->
    <style>
        /* Add your custom styles here */
    </style>
</head>

<body>
    <div class="fakeLoader"></div>

    <nav class="navbar navbar-expand-lg header-shadow bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand text-white" href="">
                <b>Supervisor</b>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars text-white"></i>
            </button>

           
            <div class="widget-subheading">Welcome   <b>{{ admin2.username }} </b></div>
       


        <ul>
            <ul class="dropdown nav-item">
                <a href="{% url 'diagnostic_centers:admin-logout' %}" tabindex="0"
                    class="nav-link text-white">Logout</a>
            </ul>
            {% comment %} <ul class="dropdown nav-item">
                <a href="http://127.0.0.1:8000/chat/supervisor-room/{{ admin2.username }}/" tabindex="0"
                    class="nav-link text-white">Chat</a>
            </ul> {% endcomment %}
        </ul>  </div>
        </div>
    </nav>

  
    <div class="container">
        <br>
        <div class="row">
            <div class="col-md-12">
                <h2>Welcome to Supervisor Dashboard!</h2>

            </div>
            <hr>
        
            <div class="col-md-15">
              <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                      <thead class="bg-primary text-white">
                          <tr>
                              <th>Supervisor</th>
                              <th>Students</th>
                              <th>Topic</th>
                              <th>Description</th>
                              <th>Uploaded Proposal</th>
                              <th>Approved</th>
                              <th>Chat</th>
                          </tr>
                      </thead>
                      <tbody>
                        {% for student in students %}

                                <tr>
                                    <td>{{ student.Supervisor }}</td>
                                    <td>{{ student.Student1 }}, {{ student.Student2 }}, {{ student.Student3 }}</td>
                                    <td>{{ student.Title }}</td>
                                    {% with project_available=False %}
                                        {% for project_upload in project_uploads %}
                                            {% if project_upload.user == admin2.username or project_upload.user == student.Student1 or project_upload.user == student.Student2 or project_upload.user == student.Student3 %}
                                                {% with project_available2=True %}
                                                    <td>{{ project_upload.description }}</td>
                                                    <td><a href="{{ project_upload.upload_file.url }}">View File</a></td>
                                                    <td>{% if project_upload.approved %}Approved{% else %}<a href="{% url 'diagnostic_centers:project_approval' project_upload.id admin2.username %}" disabled>Approval</a> {% endif %}</td>
                                                    <td><a href="http://127.0.0.1:8000/chat/supervisor-room/{{ admin2.username }}/{{ student.sid }}">Chat</a></td>
                                                {% endwith %}
                                                
                                            {% endif %}
                                        {% endfor %}
                                        {% if project_available == False %}
                                                <td colspan="3">N/A</td>
                                                <td><a href="http://127.0.0.1:8000/chat/supervisor-room/{{ admin2.username }}/{{ student.sid }}">Chat</a></td>
                                        {% endif %}
                                    {% endwith %}

                                    
                                </tr>
                        {% empty %}
                            <tr>
                                <td colspan="8">No Group Assigned As Yet.</td>
                            </tr>
                        {% endfor %}
                      </tbody>
                  </table>
              </div>
          </div>
          

    

<hr>

{% comment %} <div class="container">
  <table class="table table-striped">
    <thead class="bg-primary text-white">
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>File</th>
        <th>Remarks</th>
        <!-- <th>Approval</th> -->
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      {% for project_upload in project_uploads %}
      <!-- <td><a href="http://127.0.0.1:8000/project_approval/{{ project_upload.id }}" target="_blank">Approval</a></td> -->
      
        <tr>
          <td>{{ project_upload.title }}</td>
          <td>{{ project_upload.description }}</td>
          <td><a href="{{ project_upload.upload_file.url }}">{{ project_upload.upload_file.name }}</a></td>
          <td>{{ project_upload.remarks }}</td>
          <!-- <td>{{ project_upload.approved }}</td> -->
          <!-- <td><a href="http://127.0.0.1:8000/project_approval/{{ project_upload.id }}" target="_blank">Approval</a></td> -->


{% if project_upload.approved %}
  <td>Already Approved</td>
{% else %}
  <td><a href="http://127.0.0.1:8000/project_approval/{{ project_upload.id }}" disabled>Approval</a></td>
{% endif %}


        </tr>
     
    {% empty %}
      <tr>
        <td colspan="4">No projects found.</td>
      </tr>
    {% endfor %}
    
    </tbody>
  </table>
</div> {% endcomment %}



  
 
<br>
<br>
<br>


    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <script>
    </script>
</body>

</html>

templates/diagnostic_centers/admin_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Supervisor Login</title>
    <!-- Add Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <!-- Add your custom CSS styles if needed -->
    <style>
        /* Add your custom styles here */
        .login-bg {
            background-color: #f8f9fa;
            height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .log-box {
            max-width: 400px;
            margin: 0 auto;
            background-color: #fff;
            border-radius: 10px;
        }

        .login-btn {
            width: 100%;
        }
    </style>
</head>

<body style="background-color: #D3D3D3;">
	<div class="fakeLoader"></div>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<div class="container">
			<a class="navbar-brand" href="{% url 'home' %}"><b>LMS System</b></a>
			<button class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent"
				aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item">
	
					</li>
			
					<li class="nav-item">
						<a class="nav-link" href="http://127.0.0.1:8000/">Home</a>
					</li>

					{% if user.is_authenticated %}
					<li class="nav-item dropdown user-profile">
						<a class="nav-link dropdown-toggle d-flex align-items-center" href="#" role="button"
							data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<img src="{{ user.customer_profile.image.url }}" alt="" class="rounded-circle"
								style="width: 30px; height: 30px;">
							<span class="ml-2">{{ user.username }}</span>
						</a>

						<div class="dropdown-menu dropdown-menu-right">
							<div class="dropdown-header text-center">
								<img src="{{ user.customer_profile.image.url }}" alt="" class="rounded-circle"
									style="width: 80px; height: 80px;">
								<p>{{ user.customer_profile.profile_name }}</p>
								<a href="{% url 'custom_users:profile-edit' %}" class="btn btn-primary btn-sm">
									Edit Profile
								</a>
							</div>
							<div class="dropdown-divider"></div>
							
					
							<a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a>
						</div>
					</li>
					{% else %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'account_login' %}">Student Login</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="http://127.0.0.1:8000/supervisor-login/">Supervisor Login</a>
					</li>
					{% endif %}
				</ul>
			</div>
		</div>
	</nav>







    <div class="login-bg">
        <div class="container">

            <div class="card log-box text-center my-">
                <div class="card-body py-4">

                    <h3 class="mb-0">Supervisor Login</h3>

                    <form method="post" class="login">
                        {% csrf_token %}

                        {{ admin_login_form.as_p }}

                        <button class="btn login-btn btn-s px-5 mt-3 btn-primary" type="submit">LOGIN</button>
                    </form>
                </div>

            </div>
        </div>
    </div>

    <!-- Add Bootstrap JS and jQuery -->
    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <!-- Add your custom JavaScript code if needed -->
    <script>
        // Add your custom scripts here
    </script>
</body>

</html>

templates/diagnostic_centers/center_details.html
{% extends 'base.html' %}

{% block title %}Center Details | ODLRS{% endblock %}

{% block content %}


<div class="inner-content">
    <div class="container">

        <!-- all tests -->
        <div class="row">
            {% for test in tests_by_center %}
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="card test-box">
                    <div class="card-title">
                        <img src="{{ test.image.url }}" class="card-img-top" alt="..." width="100%">
                    </div>

                    <div class="card-body">
                        <p class="card-subtitle mb-2 text-muted">{{ test.category }}</p>

                        <h6 class="">
                            <a href="{% url 'tests:test-details' test.id %}">{{ test.test_name }}</a>
                        </h6>

                        <p class="card-text">{{ test.center }}</p>


                        <p class="card-text text-dange price">Price: <span id="price">{{ test.price }}</span> TK</p>
                        <!-- <p class="card-text">{{ test.active_status }}</p> -->

                        <a class="btn btn-sm order-btn text-center" href="{% url 'tests:order' test.id %}"
                            type="submit">
                            ORDER
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <!-- <hr>
        <h3 style="color: orangered"><b>All Tests Of This Center</b></h3>
        <hr> -->

        <!-- {% for test in tests_by_center %}

        <li><a href="{% url 'tests:test-details' test.id %}"><strong>{{ test.test_name }}</strong></a></li>

        {% endfor %}
        <br> -->
    </div>

</div>

{% endblock %}

templates/diagnostic_centers/edit_new_project_group.html
  


{% load static %}


<!doctype html>
<html lang="en">

<head>
    <title>Supervisor Dashboard</title>
    <!-- Add Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <!-- Add your custom CSS styles if needed -->
    <style>
        /* Add your custom styles here */
    </style>
</head>

<body>
    <div class="fakeLoader"></div>

    <nav class="navbar navbar-expand-lg header-shadow bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand text-white" href="">
                <b>Supervisor</b>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars text-white"></i>
            </button>

           
            <div class="widget-subheading">Welcome {{ admin.username }}</div>
        <ul>
            <ul class="dropdown nav-item">
                <a href="{% url 'diagnostic_centers:admin-logout' %}" tabindex="0"
                    class="nav-link text-white">Logout</a>
            </ul>

        </ul>

                   </div>
        </div>
    </nav>

  

    <h2 class="text-center">Add Remarks on Notice Board</h2>

<!-- <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <h2 class="text-center">Edit Group</h2>
        <form method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="{{ form.supervisor.id_for_label }}">Supervisor:</label>
            {{ form.supervisor }}
          </div>
          <div class="form-group">
            <label for="{{ form.student1.id_for_label }}">Student 1:</label>
            {{ form.student1 }}
          </div>
          <div class="form-group">
            <label for="{{ form.student2.id_for_label }}">Student 2:</label>
            {{ form.student2 }}
          </div>
          <div class="form-group">
            <label for="{{ form.student3.id_for_label }}">Student 3:</label>
            {{ form.student3 }}
          </div>
          <div class="form-group">
            <label for="{{ form.prediction.id_for_label }}">Prediction:</label>
            {{ form.prediction }}
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </form> -->
        <hr>
       
        <form method="POST">
          {% csrf_token %}
          <div class="form-group">
            <label for="{{ form.notice.id_for_label }}">Notice:</label>
            {{ form.notice }}
          </div>
          <div class="text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  
<hr>

 

<br>
<br>
<br>


    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <script>
    </script>
</body>

</html>